### ISSUE TITLE
Compilation albums not indexed correctly

### ISSUE THREAD

**Issue by amp64** [amp64/sonosbugtracker#7]
New for the .05 release, albums with multiple contributing artists are no longer indexed correctly.

**Comment by amp64** [comment]
Fixed in firmware 16.4.2. (Why did it take 2 months?)

**Comment by bluegaspode** [comment]
At least for some (eventually) corner cases this is still not fixed or different to the past. 
I compare the S1 indexing with current S2 (firmware 16.4.4).

Case 1: 
Folder with album tracks, tracks have all the same "Album" tag, but on some tracks the "Artist" mentions collaborations. 
So no distinct "Artist" and "Album artist" is empty.

S1: the albums list, the albums is listed just once, with all tracks on the next level. The rendered artist name in the albums list is eventually from the first track
S2: in the albums list I see the album three times, with the same name (and all variations of artists). Yet the album still is splittet

Case 2: 
Folder with three tracks, album artist is "Various Artists", but we have "Artist" Tags, which reference multiple artists.
<img width="778" alt="image" src="https://github.com/user-attachments/assets/5572e64d-371b-4db4-9832-d458cd44bbe3">

In the S2 Albums list this album is now listed 5 times 

<img width="408" alt="image" src="https://github.com/user-attachments/assets/37abd670-8605-4a46-9f78-929d5c67e41d">


S1 just showed it once in the albums list, with the first artist as a reference: 
<img width="424" alt="image" src="https://github.com/user-attachments/assets/4e060d38-3d19-481a-b4b2-0c860b08bae5">

**Comment by amp64** [comment]
Sonos have now documented the change and now expect some compilation albums to be tagged to work as they used to (why did they change this??). Anyway, [official answer is here](https://en.community.sonos.com/controllers-and-music-services-229131/music-library-compilation-issue-under-new-16-3-firmware-6899802/index8.html?postid=16833352#post16833352)
